version: '3.8'

services:
  rabbit-mq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
       - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
       - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq/
    networks:
      - bantads-network
    restart: on-failure:3

  ms-account:
    build:
      context: ./bantads-ms-account
      dockerfile: ./Dockerfile
    env_file:
      - ./bantads-ms-account/.env

  ms-authentication:
    build:
      context: ./bantads-ms-authentication
      dockerfile: ./Dockerfile
    env_file:
      - ./bantads-ms-authentication/.env
    depends_on:
      - rabbit-mq

  ms-client:
    build:
      context: ./bantads-ms-client
      dockerfile: ./Dockerfile
    env_file:
      - ./bantads-ms-client/.env
    depends_on:
      - rabbit-mq

  ms-manager:
    build:
      context: ./bantads-ms-manager
      dockerfile: ./Dockerfile
    env_file:
      - ./bantads-ms-manager/.env

  saga-register:
    build:
      context: ./saga-register
      dockerfile: ./Dockerfile
    env_file:
      - ./saga-register/.env
    depends_on:
      - rabbit-mq