version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ms_account:
    build: .
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  postgres_data:
    name: postgres_data
