version: '3.8'
services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    env_file:
      - .env
    ports:
      - "5433:5432"
    networks:
      - bantads-network

  ms-client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ms-client
    env_file:
      - .env
    ports:
      - "3002:3002"
    depends_on:
      - postgres-db
    networks:
      - bantads-network
    restart: on-failure

networks:
  bantads-network:
    driver: bridge
